import { ProjectVersionInput } from "./types";

interface RuleCondition {
  fieldName: string;
  operator: string;
  compareValue: string;
}

interface Rule {
  ruleCode: string;
  outputTarget: string | null;
  conditions: RuleCondition[];
}

function evaluateCondition(
  condition: RuleCondition,
  input: ProjectVersionInput
): boolean {
  const fieldMap: Record<string, string | number | boolean> = {
    floorsAboveGround: input.floorsAboveGround,
    floorsBelowGround: input.floorsBelowGround,
    projectType: input.projectTypeCode,
    renovationScope: input.renovationScopeCode ?? "",
    finishLevel: input.finishLevelCode,
    regionCode: input.regionCode,
    energyStandard: input.energyStandardCode ?? "",
    heatingType: input.heatingType,
  };

  const fieldValue = fieldMap[condition.fieldName];
  const compareValue = condition.compareValue;

  switch (condition.operator) {
    case "eq":   return String(fieldValue) === compareValue;
    case "neq":  return String(fieldValue) !== compareValue;
    case "gte":  return Number(fieldValue) >= Number(compareValue);
    case "lte":  return Number(fieldValue) <= Number(compareValue);
    case "gt":   return Number(fieldValue) > Number(compareValue);
    case "lt":   return Number(fieldValue) < Number(compareValue);
    case "in":   return compareValue.split(",").includes(String(fieldValue));
    default:     return false;
  }
}

function evaluateRule(rule: Rule, input: ProjectVersionInput): boolean {
  return rule.conditions.every((c) => evaluateCondition(c, input));
}

export interface RuleEffects {
  activateLots: string[];
  deactivateLots: string[];
  /** Accumulated multipliers per lot code (multiple rules accumulate by multiplication) */
  lotCoefficientOverrides: Record<string, number>;
  contingencyUplift: number;
  /** Warnings generated by informational rules (RE2020, etc.) */
  warnings: string[];
}

export function applyRules(rules: Rule[], input: ProjectVersionInput): RuleEffects {
  const effects: RuleEffects = {
    activateLots: [],
    deactivateLots: [],
    lotCoefficientOverrides: {},
    contingencyUplift: 0,
    warnings: [],
  };

  for (const rule of rules) {
    if (!evaluateRule(rule, input)) continue;

    const output = rule.outputTarget ?? "";

    if (output.startsWith("activate_lot:")) {
      effects.activateLots.push(output.slice("activate_lot:".length));

    } else if (output.startsWith("deactivate_lot:")) {
      effects.deactivateLots.push(output.slice("deactivate_lot:".length));

    } else if (output.startsWith("increase_coef:")) {
      // Format: increase_coef:<lotCode>:<factor>
      const parts = output.split(":");
      const lotCode = parts[1];
      const factor = parseFloat(parts[2]);
      if (lotCode && Number.isFinite(factor) && factor > 0) {
        // Accumulate by multiplication so multiple rules on the same lot compound
        effects.lotCoefficientOverrides[lotCode] =
          (effects.lotCoefficientOverrides[lotCode] ?? 1.0) * factor;
      }

    } else if (output.startsWith("increase_contingency:")) {
      const uplift = parseFloat(output.split(":")[1]);
      if (Number.isFinite(uplift)) {
        effects.contingencyUplift += uplift;
      }

    } else if (output.startsWith("set_region_coef:")) {
      // IDF coefficient override: already handled via RegionalCoefficient table.
      // This rule acts as a validation/logging signal only.
      effects.warnings.push(
        `Rule ${rule.ruleCode}: region coefficient override noted (${output})`
      );

    } else if (output.startsWith("require_selection:")) {
      // RE2020 / energy enforcement: flag as warning — UI can surface this.
      const field = output.slice("require_selection:".length);
      effects.warnings.push(
        `Rule ${rule.ruleCode}: selection required for field "${field}"`
      );
    }
  }

  return effects;
}
