import type { Rule } from "./types";

export const RULES: Rule[] = [
  {
    rule_code: "RULE_REGION_IDF",
    label: "Ile-de-France bolgesel katsayi",
    type: "condition",
    priority: 100,
    condition: { region: "IDF" },
    action: { set_region_coef: 1.28, apply_on: "travaux_ht_only" },
  },
  {
    rule_code: "RULE_PROJECT_NEW_BUILD",
    label: "Yeni yapi zorunlu lotlar",
    type: "condition",
    priority: 200,
    condition: { project_type: "new_build" },
    action: {
      require_lots: [
        "terrassement",
        "fondations",
        "structure",
        "charpente",
        "couverture",
        "menuiseries_exterieures",
        "isolation",
        "cloisons",
        "revetements",
        "peinture",
        "electricite",
        "plomberie",
        "chauffage",
        "ventilation",
        "vrd",
      ],
    },
  },
  {
    rule_code: "RULE_RENOV_LIGHT",
    label: "Hafif renovasyon",
    type: "condition",
    priority: 210,
    condition: { project_type: "light_renovation" },
    action: { increase_contingency: 0.05 },
  },
  {
    rule_code: "RULE_RENOV_HEAVY",
    label: "Agir renovasyon",
    type: "condition",
    priority: 220,
    condition: { project_type: "heavy_renovation" },
    action: {
      increase_contingency: 0.15,
      activate_lots: ["demolition", "curage", "reprises_structurelles"],
    },
  },
  {
    rule_code: "RULE_MIN_TECHNICAL_LOTS",
    label: "Teknik lot zorunlulugu",
    type: "condition",
    priority: 300,
    condition: { project_type_in: ["new_build", "light_renovation", "heavy_renovation"] },
    action: { require_lots: ["electricite", "plomberie"] },
  },
  {
    rule_code: "RULE_HEATING_REQUIRED",
    label: "Isitma sistemi zorunlulugu",
    type: "condition",
    priority: 310,
    condition: { heated_area_m2_gt: 20 },
    action: { require_one_of_lots: ["chauffage", "heat_pump"] },
  },
  {
    rule_code: "RULE_BATHROOM_PLUMBING",
    label: "Banyo varsa plomberie",
    type: "condition",
    priority: 320,
    condition: { bathroom_count_gt: 0 },
    action: { require_lots: ["plomberie"] },
  },
  {
    rule_code: "RULE_KITCHEN_CONNECTIONS",
    label: "Mutfak varsa plomberie + electricite",
    type: "condition",
    priority: 330,
    condition: { kitchen: true },
    action: { require_lots: ["plomberie", "electricite"] },
  },
  {
    rule_code: "RULE_BASEMENT_IMPACT",
    label: "Bodrum etkisi",
    type: "condition",
    priority: 400,
    condition: { has_basement: true },
    action: {
      increase_coef: {
        terrassement: 1.35,
        fondations: 1.25,
        structure: 1.15,
        etancheite: 1.4,
        vrd: 1.1,
      },
    },
  },
  {
    rule_code: "RULE_ELEVATOR_4_FLOORS",
    label: "Asansor (4+ kat)",
    type: "trigger",
    priority: 410,
    condition: { floors_gte: 4 },
    action: { activate_lots: ["ascenseur"] },
  },
  {
    rule_code: "RULE_STRUCTURE_HEIGHT",
    label: "Kat sayisi etkisi",
    type: "condition",
    priority: 420,
    condition: { floors_gte: 3 },
    action: { increase_coef: { structure: 1.1, fondations: 1.08 } },
  },
  {
    rule_code: "RULE_RE2020_REQUIRED",
    label: "RE2020 zorunlu",
    type: "condition",
    priority: 500,
    condition: { project_type: "new_build", country: "FR" },
    action: { require_selection: ["energy_package"] },
  },
  {
    rule_code: "RULE_RE2020_STANDARD",
    label: "RE2020 standard",
    type: "condition",
    priority: 510,
    condition: { energy_package: "standard" },
    action: {
      increase_coef: {
        isolation: 1.12,
        menuiseries_exterieures: 1.08,
        ventilation: 1.15,
      },
    },
  },
  {
    rule_code: "RULE_RE2020_ADVANCED",
    label: "RE2020 advanced",
    type: "condition",
    priority: 520,
    condition: { energy_package: "advanced" },
    action: {
      increase_coef: {
        isolation: 1.18,
        menuiseries_exterieures: 1.12,
        ventilation: 1.2,
        chauffage: 1.15,
      },
      activate_lots: ["heat_pump", "double_flux"],
    },
  },
  {
    rule_code: "RULE_PREMIUM_FINISH",
    label: "Premium",
    type: "condition",
    priority: 600,
    condition: { finish_level: "premium" },
    action: {
      increase_coef: {
        revetements: 1.3,
        menuiseries_interieures: 1.2,
        menuiseries_exterieures: 1.15,
        plomberie: 1.2,
        electricite: 1.1,
        peinture: 1.1,
      },
    },
  },
  {
    rule_code: "RULE_LUXURY_FINISH",
    label: "Luxury",
    type: "condition",
    priority: 610,
    condition: { finish_level: "luxury" },
    action: {
      increase_coef: {
        revetements: 1.65,
        menuiseries_interieures: 1.5,
        menuiseries_exterieures: 1.35,
        plomberie: 1.4,
        electricite: 1.25,
        peinture: 1.2,
        escalier: 1.35,
      },
    },
  },
  {
    rule_code: "RULE_SMALL_SURFACE",
    label: "Kucuk proje",
    type: "condition",
    priority: 700,
    condition: { surface_m2_lt: 80 },
    action: { increase_global_coef: 1.2 },
  },
  {
    rule_code: "RULE_LARGE_SURFACE",
    label: "Buyuk proje",
    type: "condition",
    priority: 720,
    condition: { surface_m2_gt: 150 },
    action: { decrease_global_coef: 0.05 },
  },
  {
    rule_code: "RULE_DENSE_URBAN_SITE",
    label: "Yogun kentsel alan",
    type: "condition",
    priority: 800,
    condition: { site_access: "difficult" },
    action: {
      increase_coef: { terrassement: 1.15, structure: 1.08, vrd: 1.1 },
      increase_contingency: 0.03,
    },
  },
  {
    rule_code: "RULE_VERY_DIFFICULT_ACCESS",
    label: "Cok zor saha erisimi",
    type: "condition",
    priority: 810,
    condition: { site_access: "very_difficult" },
    action: {
      increase_coef: { terrassement: 1.25, structure: 1.12, vrd: 1.15 },
      increase_contingency: 0.05,
    },
  },
];
